version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine

  redis:
    image: redis:alpine

  zipkin:
    image: openzipkin/zipkin-slim:latest

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0

  sqldata:
    image: mcr.microsoft.com/azure-sql-edge

  dapr-placement:
    image: "daprio/dapr:1.9.4"

  web.httpaggregator.api:
    image: ${DOCKER_REGISTRY-}webhttpaggregatorapi
    build:
      context: .
      dockerfile: src/ApiGateways/Aggregators/Web.HttpAggregator.Api/Dockerfile

  web.httpaggregator.api.dapr:
    image: "daprio/daprd:1.9.4"
    network_mode: "service:web.httpaggregator.api"
    depends_on:
      - web.httpaggregator.api

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: src/Services/Basket/Basket.API/Dockerfile

  basket.api.dapr:
    image: "daprio/daprd:1.9.4"
    network_mode: "service:basket.api"
    depends_on:
      - basket.api

  order.api:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: src/Services/Order/Order.API/Dockerfile

  order.api.dapr:
    image: "daprio/daprd:1.9.4"
    network_mode: "service:order.api"
    depends_on:
      - order.api

  payment.api:
    image: ${DOCKER_REGISTRY-}paymentapi
    build:
      context: .
      dockerfile: src/Services/Payment/Payment.API/Dockerfile

  payment.api.dapr:
    image: "daprio/daprd:1.9.4"
    network_mode: "service:payment.api"
    depends_on:
      - payment.api

  product.api:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: src/Services/Product/Product.API/Dockerfile

  product.api.dapr:
    image: "daprio/daprd:1.9.4"
    network_mode: "service:product.api"
    depends_on:
      - product.api

